name: wikibroker_openapi_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.4

# Add regular dependencies here.
dependencies:
  uuid: ^4.5.3
  # path: ^1.9.0

dev_dependencies:
  dio: ^5.9.2
  http: ^1.6.0
  lints: ^6.0.0
  test: ^1.25.6
